# Docker compose file to orchestrate bringing ctdb up and down

version: "3.1"

services:
  db:
    container_name: ctdb_postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "ctdb"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  api:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "3000:3000"

    
volumes:
  postgres_data:
